---
fixtures:
  repositories:
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    systemd: https://github.com/simp/puppet-systemd
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch:  master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
  symlinks:
    useradd: "#{source_dir}"
