---
HOSTS:
  el8:
    roles:
    - server
    - default
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      chef-current:
        baseurl: https://packages.chef.io/repos/yum/current/el/8/$basearch
        gpgkeys:
        - https://packages.chef.io/chef.asc
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  el7:
    roles:
    - server
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      chef-current:
        baseurl: https://packages.chef.io/repos/yum/current/el/7/$basearch
        gpgkeys:
        - https://packages.chef.io/chef.asc
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
